/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root'
import { Route as QrVerificationRouteImport } from './routes/qr-verification'
import { Route as IndexRouteImport } from './routes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const QrVerificationRoute = QrVerificationRouteImport.update({
  id: '/qr-verification',
  path: '/qr-verification',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qr-verification': typeof QrVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qr-verification': typeof QrVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/qr-verification': typeof QrVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/qr-verification'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/qr-verification'
  id: '__root__' | '/' | '/qr-verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QrVerificationRoute: typeof QrVerificationRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-verification': {
      id: '/qr-verification'
      path: '/qr-verification'
      fullPath: '/qr-verification'
      preLoaderRoute: typeof QrVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QrVerificationRoute: QrVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
